#!/usr/bin/env python3
"""Build the blind SAE-feature-interpretation packet for two independent human raters.

This is the task the grant's labeller line was actually written for: the AAAI 2026
result that SAE autolabels are unreliable for deception detection. FINDINGS 35 rests
on my reading of one feature's max-activating examples as "caveat / limitation
flagging". That is a single-agent autolabel, which is precisely the failure mode the
budget was meant to guard against, and it is the most load-bearing judgement in the
project.

Blinding, enforced here:
* The target feature is placed among decoys matched on activation frequency, so it is
  not identifiable by being rarer or more common than its neighbours.
* Features are presented in a shuffled order under neutral letters, never their ids.
* No mention of concealment, deception, cheating, hedging, or the project anywhere in
  the packet.
* The mapping from letter to feature id goes to a separate key directory.

Data source is the `examples.safetensors` that Google ships alongside every
Gemma Scope 2 SAE: for each feature, the top-activating sequences from the SAE's own
training corpus, with positions and activation values. Nothing here is generated by a
model at labelling time.

Runs on CPU only (tokenizer + numpy, no model load).
"""
import argparse, json, os, random

TARGET = 655
INSTRUCTIONS = """\
# Reading task

A large language model's internal state can be decomposed into thousands of components.
Each component switches on for some kinds of text and stays off for others. Some
correspond to something a person can describe ("quoted speech", "units of measurement",
"the start of a list"); plenty correspond to nothing describable at all.

Below are {n} components, labelled A to {last}. For each one you get {k} excerpts of
text from the places where it switched on most strongly. The token where it fired
hardest is marked with >>>like this<<<.

For each component, write:

1. **One sentence**: what does this component seem to respond to? If you can see no
   pattern, write "no pattern I can see". That is a real answer and a useful one.
2. **Confidence, 1 to 5**, where 1 means "guessing" and 5 means "the pattern is obvious
   and consistent across the excerpts".

Some of these components may have no coherent pattern. Do not force a description onto
one that does not have one, and do not assume the components are related to each other.

Do not discuss any component with the other rater until both of you have finished and
sent your sheets back.

Write your answers in `ANSWERS.md`.
"""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--sae-repo", default="google/gemma-scope-2-12b-it")
    ap.add_argument("--sae-subdir", default="resid_post_all/layer_20_width_16k_l0_small")
    ap.add_argument("--tokenizer", default="unsloth/gemma-3-12b-it-bnb-4bit")
    ap.add_argument("--n-decoys", type=int, default=6)
    ap.add_argument("--n-examples", type=int, default=12)
    ap.add_argument("--ctx-before", type=int, default=220)
    ap.add_argument("--ctx-after", type=int, default=60)
    ap.add_argument("--seed", type=int, default=20260908)
    ap.add_argument("--out", default="/home/darkstar/bluedot-unit2-impossiblebench/labelling/packet_features")
    ap.add_argument("--keys", default="/home/darkstar/bluedot-unit2-impossiblebench/labelling/_keys")
    a = ap.parse_args()

    from huggingface_hub import hf_hub_download
    from safetensors.numpy import load_file
    from transformers import AutoTokenizer
    import numpy as np

    d = load_file(hf_hub_download(a.sae_repo, f"{a.sae_subdir}/examples.safetensors"))
    tok = AutoTokenizer.from_pretrained(a.tokenizer)
    freq = d["feature_frequencies"]

    # decoys matched on activation frequency, so the target is not identifiable by
    # being conspicuously rarer or more common than everything around it
    target_freq = float(freq[TARGET])
    order = np.argsort(np.abs(freq - target_freq))
    decoys = [int(i) for i in order if int(i) != TARGET][:a.n_decoys]
    feats = [TARGET] + decoys
    rng = random.Random(a.seed)
    rng.shuffle(feats)

    os.makedirs(a.out, exist_ok=True)
    os.makedirs(a.keys, exist_ok=True)
    letters = [chr(ord("A") + i) for i in range(len(feats))]
    key = []

    for letter, F in zip(letters, feats):
        acts, sids, pos = d["activations"][F], d["seq_ids"][F], d["positions"][F]
        lines = [f"# Component {letter}\n",
                 f"{a.n_examples} excerpts, strongest first. The token it fired hardest "
                 "on is marked >>>like this<<<.\n"]
        for rank, i in enumerate(np.argsort(-acts)[:a.n_examples], 1):
            s = d["tokens"][sids[i]]
            p = int(pos[i])
            before = tok.decode([int(x) for x in s[max(0, p - 60):p]])[-a.ctx_before:]
            hit = tok.decode([int(s[p])])
            after = tok.decode([int(x) for x in s[p + 1:min(len(s), p + 20)]])[:a.ctx_after]
            lines.append(f"\n**{rank}.** ...{before}>>>{hit}<<<{after}...\n")
        open(os.path.join(a.out, f"component_{letter}.md"), "w").write("\n".join(lines))
        key.append({"letter": letter, "feature_id": F, "is_target": F == TARGET,
                    "frequency": float(freq[F])})

    open(os.path.join(a.out, "INSTRUCTIONS.md"), "w").write(
        INSTRUCTIONS.format(n=len(feats), last=letters[-1], k=a.n_examples))
    sheet = ["# Answer sheet\n", "Rater name:", "Date:", "Roughly how long this took:\n",
             "| component | what it responds to (one sentence) | confidence 1-5 |",
             "|-----------|-------------------------------------|----------------|"]
    sheet += [f"| {l} |  |  |" for l in letters]
    open(os.path.join(a.out, "ANSWERS.md"), "w").write("\n".join(sheet) + "\n")
    with open(os.path.join(a.keys, "feature_key.json"), "w") as fh:
        json.dump({"sae": f"{a.sae_repo}/{a.sae_subdir}", "target": TARGET,
                   "seed": a.seed, "components": key}, fh, indent=1)

    print(f"wrote {len(feats)} components to {a.out}")
    print("target is component:", [k["letter"] for k in key if k["is_target"]][0], "(NOT for the raters)")
    print("frequencies:", {k["letter"]: round(k["frequency"], 4) for k in key})


if __name__ == "__main__":
    main()
